/*
 * Copyright Krafter SAS <developer@krafter.io>
 * MIT License (see LICENSE file).
 */

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:drift/native.dart';
import 'package:flutter_fastedgy/flutter_fastedgy.dart';

/// Replays the parity cases generated by the fastedgy test suite
/// (`tests/orm/test_filter_parity.py` in the fastedgy repository, on its
/// toolkit models) against the replica compiler: the local SQL evaluation
/// must produce the ids the real FastEdgy ORM produced on PostgreSQL.
///
/// To refresh the fixtures after a Query Builder change, run that test with
/// `REGEN_PARITY=1` and `FILTER_PARITY_OUT` pointing at
/// `test/offline/fixtures/filter_parity.json` of this repository.
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  final parity =
      jsonDecode(
            File('test/offline/fixtures/filter_parity.json').readAsStringSync(),
          )
          as Map<String, dynamic>;

  final schema = LocalSchema.fromModels(
    (parity['metadata'] as Map<String, dynamic>).map(
      (name, raw) =>
          MapEntry(name, MetadataModel.fromJson(raw as Map<String, dynamic>)),
    ),
  );

  late ReplicaStore store;

  setUpAll(() async {
    store = ReplicaStore(
      databaseOpener: () => OfflineDatabase(NativeDatabase.memory()),
    );
    await store.open();

    for (final entry in (parity['records'] as Map<String, dynamic>).entries) {
      final model = schema.models[entry.key]!;
      await store.ensureModel(model);
      await store.replaceScope(
        model,
        '',
        (entry.value as List).cast<Map<String, dynamic>>(),
      );
    }
  });

  tearDownAll(() => store.close());

  for (final (index, raw) in (parity['cases'] as List).indexed) {
    final testCase = raw as Map<String, dynamic>;
    final label =
        'case #$index ${testCase['model']} '
        '${testCase['filter'] ?? ''} ${testCase['order_by'] ?? ''}';

    test(label, () async {
      final result = await store.query(
        schema,
        testCase['model'] as String,
        scope: '',
        filter: testCase['filter'],
        orderBy: testCase['order_by'],
        limit: testCase['limit'] as int?,
        offset: testCase['offset'] as int?,
      );

      final ids = result.records.map((record) => record['id']).toList();
      final expected = (testCase['expected_ids'] as List).cast<int>();

      if (testCase['ordered'] == true) {
        expect(ids, expected);
      } else {
        expect(ids.toSet(), expected.toSet());
        expect(ids.length, expected.length);
      }
    });
  }
}
